### ISSUE TITLE
crash when confirm and payment term is not set.

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#108]
It crashes when try to confirm an invoice if payment term is not set.
From v4.2 payment term is not required any more.
http://www.tryton.org/es/posts/new-tryton-release-42.html#invoicing

> The payment term is no longer required. An invoice without payment term will create a single due line at the invoice date. 

```
Traceback (most recent call last):
  File "/trytond/wsgi.py", line 47, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/trytond/protocols/dispatcher.py", line 41, in rpc
    request, database_name, *request.rpc_params)
  File "/trytond/wsgi.py", line 39, in auth_required
    return wrapped(*args, **kwargs)
  File "/trytond/protocols/wrappers.py", line 106, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/trytond/protocols/dispatcher.py", line 163, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/modules/sale/invoice.py", line 21, in wrapper
    func(cls, invoices)
  File "/trytond/modules/sale/invoice.py", line 94, in post
    super(Invoice, cls).post(invoices)
  File "/trytond/modules/purchase/invoice.py", line 21, in wrapper
    func(cls, invoices)
  File "/trytond/modules/purchase/invoice.py", line 101, in post
    super(Invoice, cls).post(invoices)
  File "/trytond/model/modelview.py", line 640, in wrapper
    return func(cls, records, *args, **kwargs)
  File "/trytond/model/workflow.py", line 34, in wrapper
    result = func(cls, filtered, *args, **kwargs)
  File "/trytond/modules/account_invoice_ar/invoice.py", line 572, in post
    invoice.do_pyafipws_request_cae()
  File "/trytond/modules/account_invoice_ar/invoice.py", line 687, in do_pyafipws_request_cae
    payments = self.payment_term.compute(self.total_amount,
AttributeError: 'NoneType' object has no attribute 'compute'
```

**Comment by lukio** [comment]
marking this ticket as closed because it was fixed on commit: b30d95f1
