### ISSUE TITLE
factura de cliente con linea no gravada o linea exenta

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#136]
Revisar el codigo de ejemplo de pyafipws:
https://github.com/reingart/pyafipws/blob/py3k/ejemplos/factura_electronica.py#L130

```Python
File "/opt/trytond/untref5/modules_extra/account_invoice_ar/tests/scenario_invoice_pos_electronic.rst", line 245, in scenario_invoice_pos_electronic.rst
Failed example:
    invoice.click('post')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest scenario_invoice_pos_electronic.rst[155]>", line 1, in <module>
        invoice.click('post')
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/.eggs/proteus-5.0.2-py3.5.egg/proteus/__init__.py", line 93, in newfunc
        return self.func(owner, [instance], *args, **kwargs)
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/.eggs/proteus-5.0.2-py3.5.egg/proteus/__init__.py", line 877, in click
        return getattr(proxy, button)([r.id for r in records], context)
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/.eggs/proteus-5.0.2-py3.5.egg/proteus/config.py", line 181, in __call__
        result = rpc.result(meth(*args, **kwargs))
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/.eggs/trytond-5.0.5-py3.5.egg/trytond/model/modelview.py", line 665, in wrapper
        return func(cls, records, *args, **kwargs)
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/.eggs/trytond-5.0.5-py3.5.egg/trytond/model/workflow.py", line 36, in wrapper
        result = func(cls, filtered, *args, **kwargs)
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/invoice.py", line 852, in post
        in error_invoices if i.transactions]),
      File "/opt/trytond/untref5/modules_extra/account_invoice_ar/.eggs/trytond-5.0.5-py3.5.egg/trytond/error.py", line 74, in raise_user_error
        raise UserError(error)
    trytond.exceptions.UserError: ('UserError', ('There was a problem at invoices IDs "1".\nCheck out error messages: "10061: La suma de los campos BaseImp en AlicIva debe ser igual al valor ingresado en ImpNeto."', ''))
```

**Comment by lukio** [comment]
Ejemplo de xml erroneo. En este caso, son dos lineas, un esta gravada al 21% y la otra no esta gravada. El ImpNeto (220) debería ser lo mismo que BaseImp del IVA. Además, en ImpTotalConc se tiene que sumar el importe de la linea no gravada.

```xml
**XmlRequest:** 
<?xml version="1.0" encoding="UTF-8"?><Cuit>20267565393</Cuit></Auth>
<FeCAEReq><FeCabReq><CantReg>1</CantReg><PtoVta>4000</PtoVta>
<CbteTipo>1</CbteTipo></FeCabReq><FeDetReq><FECAEDetRequest><Concepto>1</Concepto>
<DocTipo>80</DocTipo><DocNro>33333333339</DocNro><CbteDesde>1307</CbteDesde>
<CbteHasta>1307</CbteHasta><CbteFch>20190424</CbteFch>
<ImpTotal>262.00</ImpTotal><ImpTotConc>0.00</ImpTotConc><ImpNeto>220.00</ImpNeto>
<ImpOpEx>0.00</ImpOpEx><ImpTrib>0.00</ImpTrib><ImpIVA>42.00</ImpIVA><MonId>PES</MonId>
<MonCotiz>1.00</MonCotiz><Iva><AlicIva><Id>5</Id><BaseImp>200.00</BaseImp>
<Importe>42.00</Importe></AlicIva></Iva></FECAEDetRequest></FeDetReq></FeCAEReq>
</FECAESolicitar>\n</soap:
Body>\n</soap:Envelope>

**XmlResponse:**
<?xml version="1.0" encoding="utf-8"?><FeCabResp><Cuit>20267565393</Cuit>
<PtoVta>4000</PtoVta><CbteTipo>1</CbteTipo><FchProceso>20190424100450</FchProceso>
<CantReg>1</CantReg><Resultado>R</Resultado><Reproceso>N</Reproceso></FeCabResp>
<FeDetResp><FECAEDetResponse><Concepto>1</Concepto><DocTipo>80</DocTipo>
<DocNro>33333333339</DocNro><CbteDesde>1307</CbteDesde><CbteHasta>1307</CbteHasta>
<CbteFch>20190424</CbteFch><Resultado>R</Resultado><Observaciones>
<Obs><Code>10061</Code>
<Msg>La suma de los campos BaseImp en AlicIva debe ser igual al valor ingresado en ImpNeto.
</Msg></Obs></Observaciones><CAE /><CAEFchVto /></FECAEDetResponse></FeDetResp>
</FECAESolicitarResult></FECAESolicitarResponse></soap:Body></soap:Envelope>

**Comment by lukio** [comment]
Aclaraciones sobre no gravado y exento:
http://www.adconsultora.com.ar/impositivo-y-seguridad-social/no-gravado-y-exento-es-lo-mismo/

Seguimos con las aclaraciones de definiciones para tener en cuenta a la hora de declarar impuestos. Ayer nos ocupamos de la diferencia entre mínimo no imponible y mínimo exento.

Hoy vamos a ver si decir que algo está “No gravado” es lo mismo que decir que está “Exento”.

Primero veamos que significa “Gravado”. Este término es utilizados para los conceptos que están alcanzados por un impuesto. Decir que está alcanzado significa que la ley impositiva lo considera hecho imponible, osea que será un importe por el que habrá que pagar impuestos.

Por ende, “No gravado” será algo que la ley no lo considera para calcular impuestos.

Y ahora, ¿Qué significa “Exento”? Este término es utilizado para cuestiones que están gravadas. Están dentro del hecho imponible reconocido por la ley. Pero los legisladores (al momento de votarla) consideraron por alguna cuestión especial, que ese concepto no tendría que tributar el impuesto.

Entonces, lo “no gravado” no está dentro del hecho imponible y lo “exento” lo está, pero fue excluído por alguna cuestión especial.

**Comment by lukio** [comment]
Dicho esto, significa una linea que no esta gravada, también debemos indicarle de alguna forma que est exenta. Ejemplo, un producto puede tener el tilde de exento y que ese tilde sea llevado a la linea de factura. Obviamente, tendría que poder tildar que la linea o producto es exento si no tiene impuesto cargado.
