### ISSUE TITLE
En la version 4.2 no genera nueva factura

### ISSUE THREAD

**Issue by andres53016** [tryton-ar/account_invoice_ar#139]
Cuando quiero generar una nueva factura me genera el siguiente error:
`Traceback (most recent call last):
  File "/trytond/wsgi.py", line 47, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/trytond/protocols/dispatcher.py", line 41, in rpc
    request, database_name, *request.rpc_params)
  File "/trytond/wsgi.py", line 39, in auth_required
    return wrapped(*args, **kwargs)
  File "/trytond/protocols/wrappers.py", line 106, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/trytond/protocols/dispatcher.py", line 163, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/model/modelview.py", line 348, in fields_view_get
    result['field_childs'])
  File "/trytond/model/modelview.py", line 447, in _view_look_dom_arch
    fields_width=fields_width)
  File "/trytond/model/modelview.py", line 604, in __view_look_dom
    fields_width=fields_width, fields_attrs=fields_attrs)
  File "/trytond/model/modelview.py", line 604, in __view_look_dom
    fields_width=fields_width, fields_attrs=fields_attrs)
  File "/trytond/model/modelview.py", line 604, in __view_look_dom
    fields_width=fields_width, fields_attrs=fields_attrs)
  File "/trytond/model/modelview.py", line 604, in __view_look_dom
    fields_width=fields_width, fields_attrs=fields_attrs)
  File "/trytond/model/modelview.py", line 604, in __view_look_dom
    fields_width=fields_width, fields_attrs=fields_attrs)
  File "/trytond/model/modelview.py", line 604, in __view_look_dom
    fields_width=fields_width, fields_attrs=fields_attrs)
  File "/trytond/model/modelview.py", line 543, in __view_look_dom
    field = cls._fields[fname]
KeyError: 'annulled'`

Saludos!

**Comment by andres53016** [comment]
Actualizando todos los modulos del tryton se soluciono!
