### ISSUE TITLE
WSFEX: crash al contabilizar comprobante en moneda Libra Esterlina (UK)

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#172]
Reporta error al querer contabilizar comprobante en moneda libra esterlina (UK). Codigo de moneda en tryton: GBP.

> Traceback (most recent call last):                                                 
  File "/opt/trytond/saas42/trytond_dist/trytond/protocols/dispatcher.py", line 163, in _dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))                                 
  File "/opt/trytond/saas42/trytond_dist/trytond/modules/sale/invoice.py", line 21, in wrapper
    func(cls, invoices)                                                            
  File "/opt/trytond/saas42/trytond_dist/trytond/modules/sale/invoice.py", line 94, in post
    super(Invoice, cls).post(invoices)                                             
  File "/opt/trytond/saas42/trytond_dist/trytond/modules/purchase/invoice.py", line 21, in wrapper
    func(cls, invoices)                                                            
  File "/opt/trytond/saas42/trytond_dist/trytond/modules/purchase/invoice.py", line 101, in post
    super(Invoice, cls).post(invoices)                                             
  File "/opt/trytond/saas42/trytond_dist/trytond/model/modelview.py", line 648, in wrapper
    return func(cls, records, *args, **kwargs)                                     
  File "/opt/trytond/saas42/trytond_dist/trytond/model/workflow.py", line 34, in wrapper
    result = func(cls, filtered, *args, **kwargs)                                  
  File "/opt/trytond/saas42/trytond_dist/trytond/modules/account_invoice_ar/invoice.py", line 789, in post
    batch=False)                                                                   
  File "/opt/trytond/saas42/trytond_dist/trytond/modules/account_invoice_ar/invoice.py", line 1176, in create_pyafipws_invoice
    moneda_id = {'USD': 'DOL', 'EUR': '060'}[self.currency.code]                   
KeyError: u'GBP'

**Comment by lukio** [comment]
REL #124
