### ISSUE TITLE
crash en function do_pyafipws_request_cae

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#37]
Esto sucedió porque no tenía lineas la factura.
Claramente, no debería llegar a ese punto:

```
Traceback (most recent call last):
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondprotocolsjsonrpc.py", line 123, in _marshaled_dispatch
    response['result'] = dispatch_method(method, params)
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondprotocolsjsonrpc.py", line 156, in _dispatch
    res = dispatch(*args)
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondprotocolsdispatcher.py", line 168, in dispatch
    result = rpc.result(meth(*args, **kwargs))
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondmodelmodelview.py", line 513, in wrapper
    return func(cls, *args, **kwargs)
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondmodelworkflow.py", line 33, in wrapper
    result = func(cls, filtered, *args, **kwargs)
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondmodulesaccount_invoice_arinvoice.py", line 240, in post
    invoice.do_pyafipws_request_cae()
  File "hometryton.virtualenvstrytonlibpython2.7site-packagestrytondmodulesaccount_invoice_arinvoice.py", line 340, in do_pyafipws_request_cae
    last_payment = max(payments, key=lambda x:x[0])[0]
ValueError: max() arg is an empty sequence
```

**Comment by lukio** [comment]
Verify if this is still happening

**Comment by lukio** [comment]
Se inicializa payments como una lista si no esta definido un termino de pago.
Ademas creo un tests para validar que el comprobante pase a estado pagado si la factura se contabiliza con sin lineas.
