### ISSUE TITLE
Error de Formato al querer generar un reporte de factura confirmada

### ISSUE THREAD

**Issue by ceciliasp** [tryton-ar/account_invoice_ar#56]
Al querer generar el reporte de la Factura (ya confirmada y con CAE) aparece el siguiente error:
Traceback (most recent call last):
  File "/trytond/protocols/jsonrpc.py", line 150, in _marshaled_dispatch
    response['result'] = dispatch_method(method, params)
  File "/trytond/protocols/jsonrpc.py", line 179, in _dispatch
    res = dispatch(*args)
  File "/trytond/protocols/dispatcher.py", line 161, in dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/modules/account_invoice/invoice.py", line 2450, in execute
    res = super(InvoiceReport, cls).execute(ids, data)
  File "/trytond/report/report.py", line 144, in execute
    type, data = cls.parse(action_report, records, data, {})
  File "/trytond/modules/account_invoice_ar/invoice.py", line 706, in parse
    localcontext=localcontext)
  File "/trytond/modules/account_invoice/invoice.py", line 2479, in parse
    localcontext)
  File "/trytond/report/report.py", line 300, in parse
    data = cls.unoconv(data, report.template_extension, output_format)
  File "/trytond/report/report.py", line 320, in unoconv
    raise Exception(stderrdata)
Exception: None

La versión de invoice_ar es la 3.4.2. con la base actualizada.
Unoconv instalado. Python-UNO ya no está disponible en Python 2.7.

En acciones / informe, la extensión que aparece es Open Office Text Document. Al querer blanquearlo aparece el error "No está autorizado a cambiar este registro. Este registro pertenece a la configuración base". (ver prtscreen)
![screenshot from 2015-07-31 10 11 20](https://cloud.githubusercontent.com/assets/8114584/9008188/c4fd5074-376e-11e5-9cf9-a6a782df4e27.png)
![screenshot from 2015-07-31 10 24 29](https://cloud.githubusercontent.com/assets/8114584/9008191/c60b5d26-376e-11e5-831d-d9f014a24ebe.png)

El campo *invoice_report_format* en la tabla account_invoice está en blanco.

Gracias!

**Comment by lukio** [comment]
La posibilidad de cambiar el reporte de la factura lo posibilita este commit be724b451bf21161cfb5c293359ac86ae4b8d3df

Sobre la exception que tira unoconv hay información acá: https://bugs.tryton.org/issue2703
